# Generated by Django 4.0 on 2021-12-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='My_User',
        ),
    ]
