# Generated by Django 4.0 on 2021-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_user_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='Email',
            field=models.EmailField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='First_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='Last_Name',
            field=models.CharField(max_length=200),
        ),
    ]
